### ISSUE TITLE
Inherited method with @JsonProperty is missing in generated model schema

### ISSUE THREAD

**Issue by fangjian601** [teamcarma/swagger-jaxrs-doclet#66] opened 2015-04-05 22:20 UTC
I encountered a bug. If a method is inherited from parent class and it is annotated with @JsonProperty, the generated model schema does not contain this field. Here's an example.

```java
public abstract class BaseModel {
	@JsonProperty("_id")
	@JsonView(DBView.class)
	private final String id;

	public BaseModel() {
		this.id = IdGenerator.generateId();
	}

	@JsonProperty("id")
	@JsonView(FrontendView.class)
	public final String getId() {
		return id;
	}
}

public class UserModel extends BaseModel {
	public UserModel() {
		super();
	}
}


public class UserResource {
	@JsonView(FrontendView.class)
	public UserModel getUser(String id) {
		return UserDAO.findOne(id);
	} 
}
``` 
For above example, the generated model schema does not contain "id" field. Is this a bug?

**Comment by conorroche** [comment] 2015-05-09 15:41
@fangjian601 sorry it has taken so long to reply, I have not has spare time recently. I have committed a test case for this which doesnt use json views but does use the @json properties and the id field is generated correctly. I suspect it is therefore related to the json views. You did not give the source for the json views. It looks like the getUser method is supposed to render using the FrontendView which does not include the id property so this seems expected behaviour to me. Does the rest framework you use output the id field in the response?

**Comment by conorroche** [comment] 2015-05-21 10:47
closing as I believe this is not a bug but expected json view behaviour.

**Closed by conorroche** 2015-05-21 10:47 UTC
