### ISSUE TITLE
Support description for header params

### ISSUE THREAD

**Issue by rmpestano** [teamcarma/swagger-jaxrs-doclet#37] opened 2014-12-10 19:56 UTC
Support for description in header params, eg:

```java
 /**
   * 
   * @headerParam aParam the description
   */
  @GET
  @Path("service")
  public Response service(@HeaderParam("aParam") String aParam) {    
    return Response.ok().build();
  }

```

**Comment by conorroche** [comment] 2015-02-03 21:28
closing as not a bug

**Closed by conorroche** 2015-02-03 21:28 UTC
